sudo: true
language: go
before_script: sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'letmein'

go: 
  - 1.7.x
  - 1.8.x
  - 1.9.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
